[package]
name = "kagi"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A simple key-value store"
repository = "https://github.com/blobcode/kagi"
categories = ["database"]
keywords = ["key-value"]

[dependencies]
ahash = "0.7.6"
bincode = "2.0.0-beta.3"
